<a href="https://colab.research.google.com/github/mateusopaiva/nba-api/blob/main/Explorando_Dados_com_a_nba_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Explorando Dados com a nba_api

## Instalação

In [1]:
!pip install nba_api

Collecting nba_api
  Downloading nba_api-1.6.1-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: numpy<2.0.0,>=1.22.2 in /usr/local/lib/python3.10/dist-packages (from nba_api) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.10/dist-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Downloading nba_api-1.6.1-py3-none-any.whl (279 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 279.4/279.4 kB 3.5 MB/s eta 0:00:00
Installing collected packages: nba_api
Successfully installed nba_api-1.6.1

In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

## Estatísticas de Carreira: Desempenho de LeBron James

In [3]:
from nba_api.stats.endpoints import playercareerstats
from nba_api.stats.static import players

# Defina o nome do jogador
nome_jogador = "LeBron James"

# Encontrar o ID do jogador usando o nome
jogadores = players.get_players()
jogador = next(player for player in jogadores if player['full_name'] == nome_jogador)
id_jogador = jogador['id']

# Obter as estatísticas de carreira do jogador
carreira = playercareerstats.PlayerCareerStats(player_id=id_jogador)

# Acessar os dados em formato DataFrame
df_carreira = carreira.get_data_frames()[0]
df_carreira

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2003-04,00,1610612739,CLE,19.0,79,79,3120.0,622,1492,0.417,63,217,0.290,347,460,0.754,99,333,432,465,130,58,273,149,1654
1,2544,2004-05,00,1610612739,CLE,20.0,80,80,3388.0,795,1684,0.472,108,308,0.351,477,636,0.750,111,477,588,577,177,52,262,146,2175
2,2544,2005-06,00,1610612739,CLE,21.0,79,79,3361.0,875,1823,0.480,127,379,0.335,601,814,0.738,75,481,556,521,123,66,260,181,2478
3,2544,2006-07,00,1610612739,CLE,22.0,78,78,3190.0,772,1621,0.476,99,310,0.319,489,701,0.698,83,443,526,470,125,55,250,171,2132
4,2544,2007-08,00,1610612739,CLE,23.0,75,74,3027.0,794,1642,0.484,113,359,0.315,549,771,0.712,133,459,592,539,138,81,255,165,2250
5,2544,2008-09,00,1610612739,CLE,24.0,81,81,3054.0,789,1613,0.489,132,384,0.344,594,762,0.780,106,507,613,587,137,93,241,139,2304
6,2544,2009-10,00,1610612739,CLE,25.0,76,76,2966.0,768,1528,0.503,129,387,0.333,593,773,0.767,71,483,554,651,125,77,261,119,2258
7,2544,2010-11,00,1610612748,MIA,26.0,79,79,3063.0,758,1485,0.510,92,279,0.330,503,663,0.759,80,510,590,554,124,50,284,163,2111
8,2544,2011-12,00,1610612748,MIA,27.0,62,62,2326.0,621,1169,0.531,54,149,0.362,387,502,0.771,94,398,492,387,115,50,213,96,1683
9,2544,2012-13,00,1610612748,MIA,28.0,76,76,2877.0,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036
10,2544,2013-14,00,1610612748,MIA,29.0,77,77,2902.0,767,1353,0.567,116,306,0.379,439,585,0.750,81,452,533,488,121,26,270,126,2089
11,2544,2014-15,00,1610612739,CLE,30.0,69,69,2493.0,624,1279,0.488,120,339,0.354,375,528,0.710,51,365,416,511,109,49,272,135,1743
12,2544,2015-16,00,1610612739,CLE,31.0,76,76,2709.0,737,1416,0.520,87,282,0.309,359,491,0.731,111,454,565,514,104,49,249,143,1920
13,2544,2016-17,00,1610612739,CLE,32.0,74,74,2795.0,736,1344,0.548,124,342,0.363,358,531,0.674,97,542,639,646,92,44,303,134,1954
14,2544,2017-18,00,1610612739,CLE,33.0,82,82,3026.0,857,1580,0.542,149,406,0.367,388,531,0.731,97,612,709,747,116,71,347,136,2251
15,2544,2018-19,00,1610612747,LAL,34.0,55,55,1937.0,558,1095,0.510,111,327,0.339,278,418,0.665,57,408,465,454,72,33,197,94,1505
16,2544,2019-20,00,1610612747,LAL,35.0,67,67,2316.0,643,1303,0.493,148,425,0.348,264,381,0.693,66,459,525,684,78,36,261,118,1698
17,2544,2020-21,00,1610612747,LAL,36.0,45,45,1504.0,422,823,0.513,104,285,0.365,178,255,0.698,29,317,346,350,48,25,168,70,1126
18,2544,2021-22,00,1610612747,LAL,37.0,56,56,2084.0,640,1221,0.524,161,448,0.359,254,336,0.756,63,396,459,349,73,59,196,121,1695
19,2544,2022-23,00,1610612747,LAL,38.0,55,54,1954.0,609,1219,0.500,121,377,0.321,251,327,0.768,65,392,457,375,50,32,178,88,1590
20,2544,2023-24,00,1610612747,LAL,39.0,71,71,2504.0,685,1269,0.540,149,363,0.410,303,404,0.750,61,457,518,589,89,38,245,78,1822
21,2544,2024-25,00,1610612747,LAL,39.0,13,13,460.0,111,216,0.514,31,72,0.431,50,66,0.758,10,102,112,120,9,6,47,17,303

##

## Registros de Jogo: Detalhes das Partidas da Temporada

In [4]:
from nba_api.stats.endpoints import leaguegamelog

gamelog = leaguegamelog.LeagueGameLog(season="2023-24", season_type_all_star='Regular Season')

# Acessar os dados em formato DataFrame
df_gamelog = gamelog.get_data_frames()[0]
df_gamelog

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22023,1610612756,PHX,Phoenix Suns,0022300062,2023-10-24,PHX @ GSW,W,240,42,95,0.442,11,33,0.333,13,17,0.765,17,43,60,23,5,7,19,22,108,4,1
1,22023,1610612747,LAL,Los Angeles Lakers,0022300061,2023-10-24,LAL @ DEN,L,240,41,90,0.456,10,29,0.345,15,20,0.750,13,31,44,23,5,4,12,18,107,-12,1
2,22023,1610612743,DEN,Denver Nuggets,0022300061,2023-10-24,DEN vs. LAL,W,240,48,91,0.527,14,34,0.412,9,12,0.750,9,33,42,29,9,6,12,15,119,12,1
3,22023,1610612744,GSW,Golden State Warriors,0022300062,2023-10-24,GSW vs. PHX,L,240,36,101,0.356,10,43,0.233,22,28,0.786,18,31,49,19,11,6,11,23,104,-4,1
4,22023,1610612739,CLE,Cleveland Cavaliers,0022300067,2023-10-25,CLE @ BKN,W,240,44,94,0.468,17,43,0.395,9,10,0.900,9,29,38,25,10,6,10,23,114,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,22023,1610612739,CLE,Cleveland Cavaliers,0022301187,2024-04-14,CLE vs. CHA,L,240,44,93,0.473,16,33,0.485,6,9,0.667,12,31,43,30,4,1,14,8,110,-10,1
2456,22023,1610612738,BOS,Boston Celtics,0022301186,2024-04-14,BOS vs. WAS,W,240,51,89,0.573,16,32,0.500,14,21,0.667,10,38,48,29,10,15,17,13,132,10,1
2457,22023,1610612747,LAL,Los Angeles Lakers,0022301195,2024-04-14,LAL @ NOP,W,240,48,87,0.552,11,29,0.379,17,18,0.944,7,32,39,32,12,3,15,13,124,16,1
2458,22023,1610612737,ATL,Atlanta Hawks,0022301188,2024-04-14,ATL @ IND,L,240,39,89,0.438,12,36,0.333,25,27,0.926,9,23,32,25,6,5,17,12,115,-42,1
2459,22023,1610612752,NYK,New York Knicks,0022301190,2024-04-14,NYK vs. CHI,W,265,46,91,0.505,12,32,0.375,16,21,0.762,16,37,53,27,7,6,21,17,120,1,1

## Desempenho das Equipes: Análise das Estatísticas dos Times

In [6]:
from nba_api.stats.endpoints import leaguedashteamstats

# Obter as estatísticas das equipes para a temporada 2023-24
team_stats = leaguedashteamstats.LeagueDashTeamStats(season="2023-24")

# Acessar os dados em formato DataFrame
df_team_stats = team_stats.get_data_frames()[0]
df_team_stats

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1610612737,Atlanta Hawks,82,36,46,0.439,3971.0,3529,7584,0.465,1125,3092,0.364,1520,1906,0.797,1024,2639,3663,2180,1110.0,615,369,461,1522,1594,9703,-179.0,1,21,21,21,3,10,2,21,6,7,17,5,7,8,3,22,6,16,16,16,26,22,15,7,5,21
1,1610612738,Boston Celtics,82,64,18,0.780,3966.0,3601,7396,0.487,1351,3482,0.388,1334,1654,0.807,876,2923,3799,2207,979.0,557,538,304,1326,1416,9887,930.0,1,1,1,1,7,4,8,8,1,1,2,19,26,7,14,1,2,14,1,27,1,1,2,30,2,1
2,1610612751,Brooklyn Nets,82,32,50,0.390,3961.0,3334,7307,0.456,1089,3010,0.362,1293,1711,0.756,938,2675,3613,2102,1076.0,556,424,409,1516,1496,9050,-237.0,1,22,22,22,10,25,16,28,9,9,19,23,20,28,7,20,11,20,12,28,12,16,13,21,25,22
3,1610612766,Charlotte Hornets,82,21,61,0.256,3946.0,3281,7133,0.460,989,2788,0.355,1189,1512,0.786,765,2538,3303,2033,1129.0,562,371,396,1472,1432,8740,-840.0,1,27,27,27,23,27,25,26,23,17,21,30,30,11,27,29,30,26,18,25,25,13,7,29,28,30
4,1610612741,Chicago Bulls,82,39,43,0.476,3996.0,3448,7339,0.470,941,2630,0.358,1369,1731,0.791,916,2677,3593,2048,1004.0,638,394,404,1541,1538,9206,-118.0,1,20,20,20,1,16,13,18,27,26,20,17,18,10,8,19,14,23,3,9,18,14,17,14,22,20
5,1610612739,Cleveland Cavaliers,82,48,34,0.585,3961.0,3425,7148,0.479,1108,3016,0.367,1278,1671,0.765,808,2742,3550,2299,1112.0,605,380,410,1436,1536,9236,198.0,1,11,11,11,10,19,24,12,7,8,15,26,24,22,22,11,17,8,17,19,21,17,5,16,20,13
6,1610612742,Dallas Mavericks,82,50,32,0.610,3941.0,3535,7352,0.481,1197,3242,0.369,1397,1842,0.758,797,2724,3521,2106,1027.0,563,406,331,1500,1667,9664,181.0,1,6,6,6,26,9,12,11,3,2,13,15,11,27,23,14,21,19,4,24,17,2,10,2,7,14
7,1610612743,Denver Nuggets,82,57,25,0.695,3941.0,3610,7279,0.496,958,2560,0.374,1240,1628,0.762,881,2762,3643,2415,1036.0,585,456,394,1489,1467,9418,431.0,1,2,2,2,26,3,17,4,25,30,10,29,29,25,13,9,7,3,5,21,10,12,9,26,14,4
8,1610612765,Detroit Pistons,82,14,68,0.171,3951.0,3353,7236,0.463,906,2602,0.348,1398,1780,0.785,861,2692,3553,2088,1248.0,531,384,490,1688,1457,9010,-747.0,1,30,30,30,21,24,20,24,29,27,26,14,15,12,15,18,16,22,28,30,20,25,28,28,27,28
9,1610612744,Golden State Warriors,82,46,36,0.561,3966.0,3582,7515,0.477,1211,3191,0.380,1282,1644,0.780,996,2834,3830,2402,1174.0,572,377,407,1598,1471,9657,214.0,1,16,16,16,7,5,3,13,2,4,7,24,27,17,5,4,1,4,23,23,23,15,22,24,8,12
10,1610612745,Houston Rockets,82,41,41,0.500,3971.0,3425,7459,0.459,1043,2964,0.352,1482,1916,0.773,940,2787,3727,2035,1045.0,639,375,482,1702,1609,9375,92.0,1,19,19,19,3,19,5,27,14,12,23,9,5,20,6,6,3,25,8,8,24,24,29,6,16,18
11,1610612754,Indiana Pacers,82,47,35,0.573,3941.0,3855,7599,0.507,1082,2891,0.374,1318,1685,0.782,827,2578,3405,2522,1059.0,631,481,440,1756,1501,10110,250.0,1,12,12,12,26,1,1,1,11,15,9,21,22,13,20,28,28,1,9,11,8,21,30,20,1,9
12,1610612746,LA Clippers,82,51,31,0.622,3941.0,3473,7108,0.489,1036,2719,0.381,1499,1817,0.825,822,2701,3523,2097,1078.0,640,413,384,1519,1537,9481,269.0,1,5,5,5,26,14,26,6,16,21,6,8,12,3,21,17,19,21,13,7,15,9,14,15,12,7
13,1610612747,Los Angeles Lakers,82,47,35,0.573,3971.0,3580,7177,0.499,969,2572,0.377,1550,1983,0.782,676,2859,3535,2340,1146.0,605,453,390,1283,1619,9679,49.0,1,12,12,12,3,6,22,2,24,28,8,2,2,15,30,2,18,5,19,19,11,11,1,4,6,19
14,1610612763,Memphis Grizzlies,82,27,55,0.329,3956.0,3145,7229,0.435,1071,3097,0.346,1316,1722,0.764,896,2598,3494,2025,1236.0,673,501,535,1563,1539,8677,-574.0,1,24,24,24,17,30,21,30,12,6,29,22,19,23,10,27,24,27,26,4,4,30,20,13,30,26
15,1610612748,Miami Heat,82,46,36,0.561,3951.0,3266,7022,0.465,1022,2765,0.370,1478,1806,0.818,766,2702,3468,2116,1038.0,617,280,388,1415,1550,9032,144.0,1,16,16,16,21,28,28,22,19,18,12,10,13,5,26,16,26,18,6,15,30,10,4,11,26,16
16,1610612749,Milwaukee Bucks,82,49,33,0.598,3961.0,3538,7258,0.487,1163,3122,0.373,1517,1960,0.774,772,2850,3622,2176,1059.0,558,413,347,1574,1576,9756,215.0,1,8,8,8,10,8,19,7,5,5,11,7,3,19,24,3,9,17,9,26,15,3,21,9,4,11
17,1610612750,Minnesota Timberwolves,82,56,26,0.683,3961.0,3383,6974,0.485,1037,2681,0.387,1461,1881,0.777,770,2807,3577,2184,1162.0,647,497,371,1544,1630,9264,529.0,1,4,4,4,10,23,29,10,15,23,3,11,8,18,25,5,15,15,22,6,5,5,18,3,18,3
18,1610612740,New Orleans Pelicans,82,49,33,0.598,3941.0,3484,7165,0.486,1023,2673,0.383,1445,1873,0.771,852,2753,3605,2210,1067.0,684,378,424,1508,1507,9436,362.0,1,8,8,8,26,12,23,9,18,24,4,13,9,21,17,10,13,13,11,3,22,19,11,18,13,6
19,1610612752,New York Knicks,82,50,32,0.610,3946.0,3385,7272,0.465,1083,2936,0.369,1396,1789,0.780,1039,2665,3704,1998,1085.0,612,336,431,1447,1565,9249,376.0,1,6,6,6,23,22,18,20,10,13,14,16,14,16,1,21,5,29,15,17,29,20,6,10,19,5
20,1610612760,Oklahoma City Thunder,82,57,25,0.695,3961.0,3653,7324,0.499,1090,2805,0.389,1451,1759,0.825,722,2725,3447,2223,1039.0,694,538,419,1545,1548,9847,608.0,1,2,2,2,10,2,15,3,8,16,1,12,17,4,29,12,27,11,7,1,1,18,19,12,3,2
21,1610612753,Orlando Magic,82,47,35,0.573,3956.0,3318,6964,0.476,903,2568,0.352,1519,2002,0.759,861,2608,3469,2023,1206.0,669,423,379,1618,1710,9058,166.0,1,12,12,12,17,26,30,15,30,29,24,6,1,26,15,25,25,28,24,5,13,7,23,1,24,15
22,1610612755,Philadelphia 76ers,82,47,35,0.573,3956.0,3404,7331,0.464,992,2733,0.363,1597,1934,0.826,906,2616,3522,2041,984.0,694,492,503,1668,1519,9397,250.0,1,12,12,12,17,21,14,23,22,19,18,1,4,2,9,23,20,24,2,1,6,27,27,17,15,9
23,1610612756,Phoenix Suns,82,49,33,0.598,3956.0,3482,7063,0.493,1020,2671,0.382,1548,1915,0.808,831,2783,3614,2218,1221.0,610,492,372,1475,1612,9532,251.0,1,8,8,8,17,13,27,5,20,25,5,3,6,6,19,7,10,12,25,18,6,6,8,5,10,8
24,1610612757,Portland Trail Blazers,82,21,61,0.256,3976.0,3227,7356,0.439,939,2723,0.345,1329,1680,0.791,1036,2469,3505,1894,1249.0,627,354,528,1654,1467,8722,-740.0,1,27,27,27,2,29,10,29,28,20,30,20,23,9,2,30,22,30,29,12,27,28,26,26,29,27
25,1610612758,Sacramento Kings,82,46,36,0.561,3971.0,3553,7455,0.477,1178,3219,0.366,1274,1710,0.745,888,2719,3607,2324,1078.0,625,342,370,1632,1504,9558,143.0,1,16,16,16,3,7,6,14,4,3,16,27,21,30,12,15,12,7,13,13,28,4,24,19,9,17
26,1610612759,San Antonio Spurs,82,22,60,0.268,3966.0,3438,7436,0.462,1036,2983,0.347,1280,1637,0.782,849,2778,3627,2449,1242.0,584,520,380,1414,1470,9192,-532.0,1,26,26,26,7,18,7,25,16,11,28,25,28,14,18,8,8,2,27,22,3,8,3,25,23,25
27,1610612761,Toronto Raptors,82,25,57,0.305,3961.0,3466,7356,0.471,942,2712,0.347,1339,1772,0.756,891,2607,3498,2335,1147.0,634,388,474,1509,1487,9213,-528.0,1,25,25,25,10,15,10,16,26,22,27,18,16,29,11,26,23,6,20,10,19,23,12,22,21,24
28,1610612762,Utah Jazz,82,31,51,0.378,3961.0,3443,7371,0.467,1060,2993,0.354,1538,1853,0.830,1002,2725,3727,2232,1285.0,537,458,528,1523,1577,9484,-401.0,1,23,23,23,10,17,9,19,13,10,22,4,10,1,4,12,3,10,30,29,9,28,16,8,11,23
29,1610612764,Washington Wizards,82,15,67,0.183,3946.0,3523,7493,0.470,1015,2915,0.348,1266,1657,0.764,755,2613,3368,2290,1147.0,623,415,496,1637,1473,9327,-762.0,1,29,29,29,23,11,4,17,21,14,25,28,25,24,28,24,29,9,20,14,14,26,25,23,17,29